version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: PM_DB
    env_file:
      - ./local.env
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    container_name: PM_APP
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ..:/app
    env_file:
      - ../core/.env
    depends_on:
      - db

volumes:
  postgres_data: